name: Chips
version: '1.1'
main: com.dola.chips.Chips
description: Password authentication plugin for Paper 1.21.11
api-version: '1.21.11'
dependencies:
  server:
    PlaceholderAPI:
      load: before
      required: false
      join-classpath: true
      
