name: Chips
version: 1.0
main: me.chips.Chips
api-version: 1.21
description: Auth plugin for Purpur 1.21.11
authors: [User]

commands:
  register:
    description: Register account
    usage: /register <password> <confirm>
    aliases: [reg]
  login:
    description: Login to account
    usage: /login <password>
    aliases: [l]
  logout:
    description: Logout
    usage: /logout
  changepassword:
    description: Change password
    usage: /changepassword <old> <new>
    aliases: [cp]
