name: Chips
version: 1.0
main: me.yourname.chips.Chips
api-version: 1.21
authors: [YourName]
description: Lightweight Auth Plugin

commands:
  register:
    description: Register an account
    usage: /register <password> <confirmPassword>
  login:
    description: Login to your account
    usage: /login <password>
